version: "3.9"
   
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    container_name: django
    build:
      context: ./TequilaElectrico-e-commerce
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./TequilaElectrico-e-commerce:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  vue:
    container_name: vue
    build:
      context: ./tequilaelectrico_app
      dockerfile: Dockerfile
    command: npm run serve
    ports: 
      - "8080:8080"
    volumes:
      - ./tequilaelectrico_app:/app

